### ISSUE TITLE
Investigate possibility for implementing Android BroadcastReceiver [4-8h]

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/VoltAir#31]
Implement support for dynamic game content.

See example at https://github.com/literacyapp-org/literacyapp-keyboard/blob/master/app/src/main/java/org/literacyapp/keyboard/receiver/StudentUpdatedReceiver.java

Investigate option for implementing similar functionality.

Can Android code be used in a game built using Qt and C++?

**Comment by diegowald** [comment]
At first glance, it is possible to call java/android code from c++. In fact, Google play services were using that.

**Comment by diegowald** [comment]
https://www.ibm.com/developerworks/java/tutorials/j-jni/j-jni.html

**Comment by jo-elimu** [comment]
@diegowald It is also necessary to modify the `AndroidManifest.xml` file (to register the BroadcastReceiver). Is this also possible using the method linked to above?

**Comment by diegowald** [comment]
@jogrimst it is not necessary to edit AndroidManifest.xml. It can be done using java code.
